### ISSUE TITLE
stops receiving data

### ISSUE THREAD

**Issue by ksullivan86** [tlskinneriv/hassio-addons#18]
I have the add on installed with hasOS but the add on only works for limited time. Of I look in the looks I don’t see any kind of error, when it stops receiving data the logs just stop even if I have it set as debug. The only solution is to restart the add on and it works again for maybe a couple hours. I have the ws-5000. Also thanks for making this, as far as I can see it’s the only answer to get local info from ambient weather stations. 

Also FYI I have everything up to date in HA

**Comment by DeFlanko** [comment]
Came here to report the same, restart the add-on, then refresh the device.... starts to work again -- stopped receiving new data 2 days ago. 

AWNET to HASS Current version: 1.1.2 

Core 2024.10.1
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.2

Ambient Weather Local 1.2.0
Device info: Weather Station WS-2902  by Ambient Weather
Firmware: AMBWeatherPro_V5.1.5

**Comment by tlskinneriv** [comment]
Apologies, I didn't intend to ghost the first raising of this issue. 

Have either of you tried to configure the MAC Address Override setting referenced in the [docs](https://github.com/tlskinneriv/hassio-addons/blob/master/awnet%2FDOCS.md)? Past issues of devices dropping off have been from an Ambient Weather update for the device that changes the way the information is sent. 

If you have already tried this, please include log information from both the addon and the integration with debug logging enabled.

**Comment by DeFlanko** [comment]
Yes nothing has changed for me since the last issue I opened, that was one
of the first things I checked!

**Comment by ksullivan86** [comment]
I was not using the mac override setting as it is clearly getting the mac but I have now added the mac in just incase. It seems like this has been an issue the whole time, I just looked at the history and it seems the addon was only working after HA restarting. I should note currently after a reboot it only seems to last for a few hours, last restart was 3 hours 5 min until it stopped receiving data.  I added a my history data you can see its a bit all over the place with timing. 
![Screenshot (253)](https://github.com/user-attachments/assets/ca633a57-eef1-49dd-919d-b7da9747bf13)
[Outside and Inside temps.csv](https://github.com/user-attachments/files/17300248/Outside.and.Inside.temps.csv)

With the temp history you can see when it fails where the data is a straight line and the logs jump to when it was next working.

Is there a way to increase the update rate, my ws-5000 can sync every 17 secs. It would be cool to have the data locally, I know data on AWN highs and lows along with wind can be off from the base station because as far as I can tell it only updates every 5 min.

On a side note it could be useful if you add a discussions area for this git, id imigne with more info more people would use this, I know many people day you cant get local ambient weather info but they are clearly wrong.

**Comment by tlskinneriv** [comment]
> I was not using the mac override setting as it is clearly getting the mac but I have now added the mac in just incase. It seems like this has been an issue the whole time, I just looked at the history and it seems the addon was only working after HA restarting. I should note currently after a reboot it only seems to last for a few hours, last restart was 3 hours 5 min until it stopped receiving data.  I added a my history data you can see its a bit all over the place with timing. 
> ![Screenshot (253)](https://github.com/user-attachments/assets/ca633a57-eef1-49dd-919d-b7da9747bf13)
> [Outside and Inside temps.csv](https://github.com/user-attachments/files/17300248/Outside.and.Inside.temps.csv)

Thanks for checking the MAC setting. After reading the report more in depth this seems like a potential connectivity or process termination problem. 

> With the temp history you can see when it fails where the data is a straight line and the logs jump to when it was next working.

Yep, definitely doesn't look regular. If possible, could you collect logs from both the addon and integration when it stops reporting? It would be beneficial for troubleshooting to know what is happening then. Also, could you provide your exact version information for HA and other components like @DeFlanko did, please? I am on 2024.9.3 and have not upgraded to 2024.10 yet. I'm wondering if the issue is update related or not. I don't have evidence of this happening on my setup (HA OS in a VM). 

> Is there a way to increase the update rate, my ws-5000 can sync every 17 secs. It would be cool to have the data locally, I know data on AWN highs and lows along with wind can be off from the base station because as far as I can tell it only updates every 5 min.

The minimum time between data updates seems to be 16 seconds based on the last time I used the app. The addon and integration handle this just fine in my environment. 

> On a side note it could be useful if you add a discussions area for this git, id imigne with more info more people would use this, I know many people day you cant get local ambient weather info but they are clearly wrong. 

I will investigate this and see if I can get something useful set up.

**Comment by DeFlanko** [comment]
i have my HAOS on a vmware vm too.

**Comment by DeFlanko** [comment]
@ksullivan86 
> Is there a way to increase the update rate, my ws-5000 can sync every 17 secs. It would be cool to have the data locally, I know data on AWN highs and lows along with wind can be off from the base station because as far as I can tell it only updates every 5 min.

When you login to the web portal of your weather station... What are your settings here:
![image](https://github.com/user-attachments/assets/f09e5b71-e4b0-441d-bf17-13a1ca88a66e)

Data does show up every min, but dashboards only ever show in increments of 5 mins. (i hate it too...)

@tlskinneriv -- looks to be 5 1/2 hours before something gives -- looking for logs now. 
![image](https://github.com/user-attachments/assets/2ef66de5-1fda-4d27-8583-7aea074f79e2)

**Comment by DeFlanko** [comment]
[8d3f9d88_awnet_to_hass_2024-10-09T01-57-10.350Z.log](https://github.com/user-attachments/files/17301020/8d3f9d88_awnet_to_hass_2024-10-09T01-57-10.350Z.log)

From Core, search for "Ambient"

```Log
This error originated from a custom integration.

Logger: custom_components.awnet_local.helpers_calc
Source: custom_components/awnet_local/helpers_calc.py:387
integration: Ambient Weather Local (documentation, issues)
First occurred: 12:13:24 PM (620 occurrences)
Last logged: 5:27:35 PM

Failed to convert timestamp "None" to datetime: time data 'None' does not match format '%Y-%m-%d %H:%M:%S'
```

**Comment by DeFlanko** [comment]
I'm not sure if its relevant or not... just an observation right now... when troubleshooting this yesterday i noticed the Host machine needing Windows updates.  i did apply them which then required a reboot (around this time), on startup I have the VM auto launch from a Windows Scheduled Task. so far no drops -- will keep an eye on it. 

![image](https://github.com/user-attachments/assets/4fa57479-fdb9-4b8b-afbb-fd2c8880d3bc)

@ksullivan86 What's your HA setup like? are you too running a VM where the host machine is Windows?

**Comment by ksullivan86** [comment]
I'm running on a pi4. Are you saying you are running HA from windows via something like vmware? That can't be a very stable setup.

**Comment by ksullivan86** [comment]
Its odd after saying the logs/ data stop after a few hours it went over 24hrs until it stopped receiving data. 
I am on:
 AWNET to HASS
Current version: 1.1.2

Core
2024.10.2
Supervisor
2024.10.0
Operating System
13.1
Frontend
20241002.3

I did just as I type upgrade core from 24.10.1 to the current 24.10.2

also I am currently trying to the weather station to 5.1.5 from 5.1.1 but its being difficult... ill let you know if the updates changed anything. As for logs its hard because by the time I see its stopped working its been many hours but ill will try

**Comment by DeFlanko** [comment]
> I'm running on a pi4. Are you saying you are running HA from windows via something like vmware? That can't be a very stable setup.

its a nice VM that HA Offers to just turn on and go... with 6 cores, and 8 GB Ram and storage of a expandable 40GB allowing for a lot of add-on flexibility when it comes to running Zigbee and an LTR-SDR radio on top of other things -- which are easily passed through from the Host machine in the VDMX file based on VID & PID. 

this host machine is a intel 13 gen i9, 64 gb ram and plenty of nvme diskspace -- which is also running my CCTV app, CodeProjects.AI instance, and in the future a Minecraft server lol .

**Comment by ksullivan86** [comment]
check out the log, the timing jumps around like crazy and I have it set to every 60 seconds.  Also I am assuming the second time stamp is the lease time or something similar.
[AWNET to HASS log.txt](https://github.com/user-attachments/files/17348580/AWNET.to.HASS.log.txt)

**Comment by ksullivan86** [comment]
> > I'm running on a pi4. Are you saying you are running HA from windows via something like vmware? That can't be a very stable setup.
> 
> its a nice VM that HA Offers to just turn on and go... with 6 cores, and 8 GB Ram and storage of a expandable 40GB allowing for a lot of add-on flexibility when it comes to running Zigbee and an LTR-SDR radio on top of other things -- which are easily passed through from the Host machine in the VDMX file based on VID & PID.
> 
> this host machine is a intel 13 gen i9, 64 gb ram and plenty of nvme diskspace -- which is also running my CCTV app, CodeProjects.AI instance, and in the future a Minecraft server lol .

why not just run proxmox? it would be better setup that running on top of windows, you can just do a windows vm or if you have to have bare metal windows(gaming) you can dual boot to windows when you have to.

**Comment by DeFlanko** [comment]
Mainly because the CCTV software only runs in Windows.

**Comment by ksullivan86** [comment]
> Mainly because the CCTV software only runs in Windows.

are you running blue iris? If I was you I would look into proxmox, if you have experience with vms it's really not that big of a learning curve to get going...specially with all the easy to follow youtube videos. I made the jump from windows to proxmox for hosting and it has been a more stable setup, I regret not doing it sooner. For example you can update and restart windows without taking down home assistant. Jim's garage has a some good content. 

on another note how did you update your console to 5.1.5? I keep getting an error that I am guessing is related to ambient weathers servers. You posted a screenshot and its updated to 5.1.5, I am stuck at 5.1.1 and I am wondering if this could be part of my problem.

**Comment by DeFlanko** [comment]
> on another note how did you update your console to 5.1.5? I keep getting an error that I am guessing is related to ambient weathers servers. You posted a screenshot and its updated to 5.1.5, I am stuck at 5.1.1 and I am wondering if this could be part of my problem.

I think it came with it.... or clicking the upgrade button worked at one point? i did just find the link to sign up for the firmware updates.

**Comment by tlskinneriv** [comment]
I have still not been able to reproduce this issue locally. Is this issue still present?

**Comment by ksullivan86** [comment]
> I have still not been able to reproduce this issue locally. Is this issue still present?

I am still having the same problem. I did just upgrade to 1.3 so maybe that has some fixes. This still only seems to work after a system restart. Then after awhile it just stops.

**Comment by tlskinneriv** [comment]
> check out the log, the timing jumps around like crazy and I have it set to every 60 seconds.  Also I am assuming the second time stamp is the lease time or something similar.
> [AWNET to HASS log.txt](https://github.com/user-attachments/files/17348580/AWNET.to.HASS.log.txt)
> 

Looking at this log again, there's no indication of errors in the add-on (it's python-based, so I'd expect some kind of exception if it was dying). I'm curious to know if the OS is even receiving the traffic. One simple thing that can be tried is navigating to the port on your HAOS install for the addon (effectively what's programmed in your weather station) in a web browser and seeing if the add-on generates any logs. Do this when the add-on appears to stop working and report back findings, please. You should expect to see warnings and errors on the add-on logs when you try this. 

The timestamp that is listed in the query string or in the data that's sent is what the weather station is provided. It looks like it's in a different time zone but matching the same time that the data is coming in.

**Comment by ksullivan86** [comment]
I'm not quite clear, am I accessing the IP if my home assistant machine that is running awnet to hass add-on or am I accessing the ip address of my weather station controller?

Also I did check and after a few hours I stoped receiving data after updating the add-on.

I am also on AMBWeatherPro_V5.1.1 I have tried to upgrade to the new version 5.1.8 but it fails. Idk if that is part of the problem or not.

**Comment by tlskinneriv** [comment]
The IP of your HA instance that's running the add-on. The same IP and port
that you have programmed in the weather station as a custom server.

**Comment by DeFlanko** [comment]
if this helps

what mine looks like on 5.1.8 no issues:
![image](https://github.com/user-attachments/assets/826d1935-6019-4eb5-9714-a7bc3ab23ada)

in HA i also have my MAC address all lowercase and with colons `xx:xx:xx:xx:xx:xx`

![image](https://github.com/user-attachments/assets/5c42e1fd-0569-47f1-a5bc-822d2e622636)

**Comment by ksullivan86** [comment]
> have

Ok I tried the IP and port and it couldn't connect and then I restarted the add-on and now a page loads It just says "missing query string". It seems something is causing the add-on to crash?

**Comment by ksullivan86** [comment]
> if this helps
> 
> 
> 
> what mine looks like on 5.1.8 no issues:
> 
> ![image](https://github.com/user-attachments/assets/826d1935-6019-4eb5-9714-a7bc3ab23ada)
> 
> 
> 
> in HA i also have my MAC address all lowercase and with colons `xx:xx:xx:xx:xx:xx`
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/5c42e1fd-0569-47f1-a5bc-822d2e622636)
> 
> 

How did you update to 5.1.8? I am stuck on 5.1.1.

**Comment by ksullivan86** [comment]
This is the log with messages from last time it stopped working. You can see at 3:07 I restarted the add-on. ![image](https://github.com/user-attachments/assets/f7ab8581-e4bd-42bb-a293-a7d49647c509)

**Comment by DeFlanko** [comment]
> > if this helps
> > what mine looks like on 5.1.8 no issues:
> > ![image](https://private-user-images.githubusercontent.com/5233969/402231270-826d1935-6019-4eb5-9714-a7bc3ab23ada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2MTMyMTQsIm5iZiI6MTczNjYxMjkxNCwicGF0aCI6Ii81MjMzOTY5LzQwMjIzMTI3MC04MjZkMTkzNS02MDE5LTRlYjUtOTcxNC1hN2JjM2FiMjNhZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTFUMTYyODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJlMDVlMzE5OTk2YjdjOTA0OWNjZmZhZTdlMzI2ZTRiZDVkYTI0ZTU3MzY0NzIyMGIzYjE2NzE1N2IzNDNlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dkN5xWtPOtcQ0RwEFoCNvCYZ-seYKBCCgJRNS7J7WnY)
> > in HA i also have my MAC address all lowercase and with colons `xx:xx:xx:xx:xx:xx`
> > ![image](https://private-user-images.githubusercontent.com/5233969/402231365-5c42e1fd-0569-47f1-a5bc-822d2e622636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2MTMyMTQsIm5iZiI6MTczNjYxMjkxNCwicGF0aCI6Ii81MjMzOTY5LzQwMjIzMTM2NS01YzQyZTFmZC0wNTY5LTQ3ZjEtYTViYy04MjJkMmU2MjI2MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTFUMTYyODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjcwYTU0MzAyODkyN2FiNmNlY2UxYjFiY2M2MTE1NGVhMmVmNGZkNWJhYjdlZmM5YjRjNWI4YTVkNWNhMjhjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pDWDf6oZkDu4MBeutGmfqLXptRH2Itd2RfxhN9SPduU)
> 
> How did you update to 5.1.8? I am stuck on 5.1.1.

Looks like i have the Auto Upgrade checked that might be why. 

![image](https://github.com/user-attachments/assets/a217c398-f1bd-4410-a6bf-f3a6218e0963)

**Comment by tlskinneriv** [comment]
> > have
> 
> Ok I tried the IP and port and it couldn't connect and then I restarted the add-on and now a page loads It just says "missing query string". It seems something is causing the add-on to crash?

The missing query string is the behavior that I expect to happen. Do you have the logs from this time? It would be very helpful for possibly debugging why the container is dying. 

I can also explore using a more robust web server than the built-in flask one that's currently in use. Not expecting more than one weather station sending data to the add-on, so one thread/request at a time should be sufficient.

**Comment by ksullivan86** [comment]
> > > have
> > 
> > Ok I tried the IP and port and it couldn't connect and then I restarted the add-on and now a page loads It just says "missing query string". It seems something is causing the add-on to crash?
> 
> The missing query string is the behavior that I expect to happen. Do you have the logs from this time? It would be very helpful for possibly debugging why the container is dying. 
> 
> I can also explore using a more robust web server than the built-in flask one that's currently in use. Not expecting more than one weather station sending data to the add-on, so one thread/request at a time should be sufficient. 

There doesn't really seem to be much info in the logs. I had the log setting set at info, it's now at debug. You can see the logs just stop around 5am. ![image](https://github.com/user-attachments/assets/64ad9106-7659-43f1-acea-ebd1417e0e3c)

**Comment by knwpsk** [comment]
Old issue, but seems to still be relevant. I'm having "same problem?"
I have WS-5000. I see that sensor data is stale in HA. I reload the integration, doesn't help. I restart this app, and everything wakes up and works again. 
Anecdotally I'd say this happens every 2-3 days (but I haven't tried very hard to log it).
I just converted from AW cloud to this app/integration about a month ago, so this is still pretty unfamiliar to me.  Happy to provide relevant logs if someone coaches me a bit on how to get them.

I'm considering writing an automation to auto-restart the app when the data sensors are stale... but hesitate to bandaid that if there's a bugfix that could resolve it. (I guess I could write the automation and have it log something too...)

**Comment by madopal** [comment]
Anecdotally, ~~the death seems to happen when the LOG line is called at line [175](https://github.com/tlskinneriv/hassio-addons/blob/master/awnet/rootfs/awnet.py#L133) (vs the LOG at line [74](https://github.com/tlskinneriv/hassio-addons/blob/master/awnet/rootfs/awnet.py#L133)).~~ (NVM, those calls happen in pairs). 

However, the [comments](https://github.com/tlskinneriv/hassio-addons/blob/master/awnet/rootfs/awnet.py#L133) for the use in that class seem to indicate maybe some more error checking would be necessary?

Also, is it possible to beef up the check for restart? I notice there's an option in there (and restarting the app, for me at least, always seems to solve it), but clearly whatever current check is happening isn't catching this case.

One more data point from me: I seem to notice that it dies more often just after a possible update shows up in HA.

**Comment by madopal** [comment]
Here's an exception I caught when it died tonight:

```
----------------------------------------
Exception occurred during processing of request from ('192.168.0.120', 55695)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socketserver.py", line 761, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/wsgiref/simple_server.py", line 114, in handle
    self.raw_requestline = self.rfile.readline(65537)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
```

**Comment by madopal** [comment]
Workaround: I made an automation that checks the time of last check. If it goes over a time limit (I set mine to 3 minutes because I have it sending every minute), it restarts the app.

```
alias: Weather data stale
description: ''
triggers:
  - entity_id:
      - [SENSOR_NAME.weatherstation_last_data_date]
    to: null
    for:
      hours: 0
      minutes: 3
      seconds: 0
    trigger: state
conditions: []
actions:
  - action: hassio.app_restart
    metadata: {}
    data:
      app: [APP_NAME_awnet_to_hass]
mode: single

```
